docs/index.md
[Issue] N/A
[Problem] Code part is not colored
[Solution] Apply correct markdown
=> Add code coloring

src/js/core/history/manager.js
[Issue] N/A
[Problem] Spelling typo
[Solution] Successfully corrected problem
=> Fix spelling typo

index.md
[Problem] Not able to test examples
[Solution] Link to examples on main page
=> Link to examples on main page

docs/guide/source/api/wearable
[Problem] Wrong symbolic link
[Solution] Removed wrong symbolic link
=> Removed wrong symbolic link

templates/mobile/Chat/lib/tau, templates/mobile/ImageGallery/lib/tau, templates/mobile/NewsList/lib, templates/wearable/Alarm/lib/tau, templates/wearable/Buddy/lib/tau, templates/wearable/Chat/lib/tau, templates/wearable/DrawerTemplate/lib, templates/wearable/ImageGallery/lib/tau, templates/wearable/InstantSettings/lib/tau, templates/wearable/LoginForm/lib/tau, templates/wearable/Mailbox/lib/tau, templates/wearable/Map/lib/tau, templates/wearable/MusicPlayer/lib/tau, templates/wearable/NewsList/lib, templates/wearable/RichNotification/lib/tau, templates/wearable/Settings/lib/wearable, templates/wearable/Shopping/lib/tau, templates/wearable/SmartThings/lib/tau, templates/wearable/Speedometer/lib/tau, templates/wearable/VideoPlayer/lib/tau, templates/wearable/VoiceRecorder/lib/tau
[Problem] Error: The symbolic link `/templates/mobile/Chat/lib/tau`
targets a file which does not exist within your site's repository
[Solution] Updated symbolic link
=> Update symbolic links

README.md
[Issue] https://github.com/Samsung/TAU/issues/22
[Problem] Unable to use global grunt 
[Solution] Use locally available grunt
=> Update README.md with steps working on Ubuntu

src/js/core/history/manager.js
[Issue] N/A
[Problem] Spelling typo
[Solution] Successfully corrected problem
=> [cherry-pick] Fix spelling typo

README.md
[Issue] N/A
[Problem] New 5.5 commands
[Solution] Update README.md with minor changes reflecting 5.5
commands:
- npm run test
- npm run build
=> Update README.md according to 5.5 changes

examples/wearable/UIComponents/contents/list/arclistview/list_arclistview.html
[Problem] ArcListview elements are not sorted alphabetically. Under 'A' letter are elements begin from 'b' letter.
[Solution] Change html of arcListview and sort elements.
Signed-off-by: Wojciech Szczepanski <w.szczepansk@samsung.com>
=> Update html of arcListview to display menu well.

examples/mobile/UIComponents/config.xml, examples/wearable/UIComponents/config.xml
[Issue] N/A
[Problem] Sampla apps should support previous Tizen versions
[Solution] Required version have been changed
=> Sample Apps: Change required version

README.md, package.json
[Issue] N/A
[Problem] Additional steps needed to run http-server
[Solution] Create appropriate entries in package.json
=> Allow user to run http-serve easily

README.md
[Problem] No up-to-date versioning information
[Solution] Propose verisioning schema. Update README.md with versioning information
=> Update README.md with versioning information

README.md
[Problem] PR https://github.com/Samsung/TAU/pull/49 merged to master
[Solution] Sync master-->tizen_4.0
=> Sync master-->tizen_4.0

examples/wearable/UIComponents/contents/list/list_selectmode.js, src/css/profile/wearable/changeable/common/listview.less, src/css/profile/wearable/changeable/theme-changeable/theme.circle.less, src/css/profile/wearable/changeable/theme-circle/arclistview.less, src/css/profile/wearable/changeable/theme-circle/marquee.less, src/js/core/widget/core/Marquee.js, src/js/profile/wearable/widget/wearable/ArcListview.js
[Problem] Text in list item is cutted, text overlaps icon
[Solution] Added marque widget for text content.
When text is too long then text is scrolled.
This change requires change in UIComponents sample app.
Selectable list needs update.
=> ArcListview: Add marquee for content of currenly selected listitem

tests/js/profile/wearable/widget/wearable/ArcListview/ArcListview.js
[Issue] https://github.com/Samsung/TAU/issues/62
[Problem] TAU unit test fails
Testing tests/js/profile/wearable/widget/wearable/ArcListview/ArcListview.html ......F................
[Solution] The unit test required change after implementation change
=> ArcListview: fix for unit test after implementation change

package.json
[Issue] N/A
[Problem] In travis CI logs:  "Error: no test specified"
[Solution] Add appropriate entry in package.json for testing
=> Add test execution

src/js/profile/wearable/widget/wearable/ArcListview.js
[Issue] https://github.com/Samsung/TAU/issues/83
[Problem] List could be scrolled with bezel when popup was shown
[Solution] Disable list after showing popup from the same
page and enable it back again after hiding it
=> Disable list after showing popup on the same page

.travis.yml, package.json
[Issue] N/A
[Problem] No eslint verification of committed files
[Solution] Use lint-diff npm package
=> Enable travis eslint check for every PR

src/js/profile/mobile/widget/mobile/Listview.js, tests/js/profile/mobile/widget/mobile/Listview/Listview.js
=> Listview: fix for many colored listviews on the same page

.travis.yml, package.json, src/js/core/history/manager.js, src/js/profile/mobile/widget/mobile/Listview.js, src/js/profile/wearable/widget/wearable/ArcListview.js
[Issue] N/A
[Problem] Some files have typo errors.
[Solution]
Enable spell check by default
Use cspell tool. Fix issues.
=> Fix spellchecking errors and enable spellcheck for every commit

src/js/core/router/route/panel.js
[Issue] N/A
[Problem] Attempt to call method on undefined caused exception.
[Solution] Fix object reference ns.router.history => ns.history
=> PanelChager: Fix hashchange event listener

examples/mobile/UIComponents/css/style.css
[Issue] https://github.com/Samsung/TAU/issues/77
[Problem] Non existing file path was used in stylesheet
[Solution] Remove references to non existing file.
=> Remove non existing file references from UIComponent app stylesheets

src/js/core/widget/core/Page.js
[Issue] https://github.com/Samsung/TAU/issues/125
[Problem] Only first title element had ui-title class added
[Solution] Add ui-title for all found title elements
=> Add ui-title class to all found title elements

src/js/profile/mobile/widget/mobile/Listview.js
[Issue] https://github.com/Samsung/TAU/issues/107
[Problem] There was not any area colored above the list.
During scrolling browser could not render
next colored fragment fast enough.
[Solution] Add colored buffer area above first list element
=> ListView: Fix blinking during fast scrolling down the list

examples/mobile/UIComponents/components/headerfooter/header/righttext.html, examples/mobile/UIComponents/components/headerfooter/header/twotext.html
[Issue] N/A
[Problem] Buttons did not have defined any action
[Solution] Add back action for back buttons
=> Add back action to back buttons

examples/mobile/UIComponents/components/list/normallist.html
[Issue] https://github.com/Samsung/TAU/issues/225
[Problem] Wrong page title in List/NormalList
[Solution] Page title has been updated
=> UIComponents: Updating the page title for List/Normal list

src/js/core/util/anchorHighlight.js, src/js/profile/mobile/widget/mobile/FloatingActions.js
[Issue] https://github.com/Samsung/TAU/issues/156
[Problem] Floating actions example - not working
[Solution]
- Added press effect for buttons in mobile profile,
- Removed unnecessary "vmouse" listeners on floating button
=> Floating Action: added press effect on vclick

examples/mobile/UIComponents/components/list/gridview/gridcheck.js
[Example][Mobile] Set checkbox state to indicate all images selected
[Issue] #231
[Problem] Select all checkbox was not checked after
manually selecting all checkboxes
[Solution] Implement such check after clicking an image
=> Set checkbox state to indicate all images selected

src/js/core/history.js, src/js/profile/wearable/widget/wearable/DatePicker.js, src/js/profile/wearable/widget/wearable/NumberPicker.js, src/js/profile/wearable/widget/wearable/TimePicker.js
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/175
[Problem] Pressing Set button causes opening previous page in web browser
[Solution] Before going back check if this is starting url for tau.
=> Don't allow to go back outside tau history

examples/mobile/UIComponents/components/gallery/gallery.js
[Issue] https://github.com/Samsung/TAU/issues/178
[Problem] After deleting currently selected section
no active index was set.
[Solution] Add setting active section after deleting picture
=> Add setting active index after delete image from gallery

examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.html, examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js, examples/mobile/UIComponents/css/style.css
[Issue] https://github.com/Samsung/TAU/issues/229
[Problem] Search button did nothing - feature was not implemented
[Solution] Add filtering list elements based on user's input
=> Add search feature to page with index scrollbar and floating button

examples/wearable/UIComponents/contents/list/arclistview/list_arclistview.html, examples/wearable/UIComponents/css/style.circle.css, src/css/profile/wearable/changeable/theme-circle/checkboxradio.less, src/css/profile/wearable/changeable/theme-circle/listview.less
[Issue] https://github.com/Samsung/TAU/issues/237
[Problem] Text and button overlap in Listview
[Solution] New css styles have been added.
=> Fix for text and button overlaping on Listview

src/js/core/util/animation/animation.js, src/js/core/widget/BaseWidget.js
[Issue] https://github.com/Samsung/TAU/issues/239
[Problem] Marquee gradient effect remains even if not necessary
[Solution] There was occured several issues in Animation module.
- marquee animation was continued despite the animation stop
- in transform method was dividing by zero this causes NaN value
=> Fix for remaining gradient effect in Marquee widget

src/css/profile/wearable/changeable/theme-circle/arclistview.less, src/css/profile/wearable/changeable/theme-circle/listview.less, src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
[Issue] N/A
[Problem] List selection style should be changed
[Solution] Remove mask image and replace background with solid color
=> [Wearable] Change list selection style

src/js/profile/mobile/widget/mobile/TextInput.js, src/js/profile/wearable/widget/wearable/TextInput.js
[Issue] https://github.com/Samsung/TAU/issues/299
[Problem] In case if focus() method was called on
textinput element cursor was placed
at the zero position
[Solution] Move cursor to the last position after focus
=> Set caret position to last element after textinput focus

examples/mobile/UIComponents/components/navigationelements/indexscrollbar.js, examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js, src/css/profile/mobile/changeable/common/listview.less, src/js/profile/mobile/widget/mobile/IndexScrollbar.js, src/js/profile/mobile/widget/mobile/Listview.js
Merge fixes from TAU 1.1 to TAU 1.0
- Listview: fix for color list with embedded lists
- IndexScrollbar: Cleaning of white spaces from index
=> Merge commits from 1.1

examples/wearable/UIComponents/contents/navcontrols/drawer.html, examples/wearable/UIComponents/contents/navcontrols/drawer.js
[Issue] https://github.com/Samsung/TAU/issues/201
[Problem] Drawer - wearable - no example in UI Components
[Solution] Drawer example has been added.
=> Drawer example in UI Components

Gruntfile.js
[Issue] https://github.com/Samsung/TAU/issues/335
[Problem] TAU bundled file had huge size and loaging time.
[Solution] Split external libraries across different files
to allow skipping unused libraries loading.
=> Add configurable bundled extensions build

src/js/core/widget/BaseWidget.js, src/js/profile/mobile/widget/mobile/DropdownMenu.js, tests/js/profile/mobile/widget/mobile/DropdownMenu/DropdownMenu.js
[Issue] Refer to https://github.com/Samsung/TAU-Design-Editor/issues/272
[Problem] Widget doesn't change visible falue on refresh
[Solution] Added placeholder update on refresh
This PR is dependent to https://github.com/Samsung/TAU/pull/351
=>  DropDownMenu: update placeholder on widget refresh

examples/mobile/UIComponents/components/controls/textinput.html, examples/wearable/UIComponents/contents/navcontrols/drawer.html, examples/wearable/UIComponents/contents/navcontrols/drawer.js, src/css/profile/mobile/changeable/common/floatingactions.less, src/js/core/engine.js, src/js/core/widget/BaseWidget.js, src/js/core/widget/core/Graph.js, src/js/core/widget/core/SectionChanger.js, src/js/core/widget/core/indexscrollbar/IndexScrollbar.js, src/js/profile/mobile/widget/mobile/DropdownMenu.js, src/js/profile/mobile/widget/mobile/TextInput.js, src/js/profile/wearable/widget/wearable/Selector.js, tests/js/core/widget/core/SectionChanger/sectionchanger.js, tests/js/profile/mobile/widget/mobile/DropdownMenu/DropdownMenu.js, tests/js/profile/mobile/widget/mobile/Listview/Listview.js
This PR contains merge of patches from TAU 1.0
and fixes for issues reported by tests (include TCT)
=> Merge patches from TAU 1.0 into TAU 1.1 & fixes

tests/tct-paker.sh, tools/grunt/tasks/tau-tct.js
[Issue] N/A
[Problem] The TCT are building for previous 5.0 version
[Solution] Modification of Tizen version in tasks
=> (tct) Change version of TCT to 5.5

src/js/core/util.js
[Issue] N/A
[Problem] Test referring to evaluate inline scripts from external sources fails
[Solution] Added feature to copy attributes
=> Utils: Added copy of attributes from original inline script to new one

src/css/profile/wearable/changeable/theme-circle/layout.less, src/css/profile/wearable/changeable/theme-circle/listview.less, src/js/core/util/scrolling.js, src/js/profile/wearable/widget/wearable/SnapListview.js
[Issue] https://github.com/Samsung/TAU/issues/342
[Problem] ui-listview-divider breaks listview
[Solution] Adding snap points definition to module of scrolling
=> SnapListview: scroll issue

src/css/profile/wearable/changeable/theme-circle/layout.less, src/css/profile/wearable/changeable/theme-circle/listview.less, src/js/core/util/scrolling.js, src/js/profile/wearable/widget/wearable/SnapListview.js
[Issue] https://github.com/Samsung/TAU/issues/342
[Problem] ui-listview-divider breaks snap listview
[Solution] Adding snap points definition to module of scrolling
=> SnapListview: scrolling issue when list has deviders (patch from branch 1.1)
