Samsung/TAU

- docs/index.md
[Problem] Start page has a lot of text, important information is not on the beginning.
No reference to WATT
[Solution] Simplify welcome page. Move less important sections to the end. Add short note about WATT
> Simplify welcome page for github docs

- docs/guide/source/api/mobile
[Problem] Documentation generation fails with error message
[Solution] Remove wrong symbloic link
> Remove wrong symbolic link

- src/css/profile/mobile/changeable/common/tabbar.less
[Issue] http://suprem.sec.samsung.net/jira/browse/SAD-527
[Problem] Tabbar: Title & icon tab displays wrongly
[Solution]
Displaying gray area is inconsistent for each web browser.
Setting of line-height style solves this issue.
[Test]
- UIComponents/components/navigationelements/tabs/tabs_icon_with_title_4.html
> Tabbar: remove gray area in tabs with title and icon

- src/js/profile/mobile/widget/mobile/DropdownMenu.js
[Problem] The popup with options in DropDownMenu widget has wrong position
[Solution] If label reffering to DropDownMenu is positioned far from widget
then popup with menu options is showing in wrong place.
This patch sets focus on DropDownMenu before show the popup.
> DropDownMenu: fix position of popup with menu options

- src/css/profile/mobile/changeable/common/textenveloper.less
[Problem] Text is cut in text Enveloper
[Solution] Position of clear button has fixed for standard text input
but in TextEvnveloper this position has to be fited to this widget.
Top position has been changed to "auto".
> TextEnveloper: fix wrong position of clear button

- src/js/profile/wearable/widget/wearable/TextInput.js
[Problem] If input already contained text cursor was always
placed at the begining of text content
[Solution] Set coursor to last position
after focusing on text input
> Textinput: Move cursor at the end of the existing text

- examples/wearable/UIComponents/contents/popup/popup_toast.html
- src/css/profile/wearable/changeable/theme-circle/popup.less
[Problem] Whole text is not visible in Toast Popup widget.
[Solution] Raise max-height of ui-popup-content class to show one more line of text.
Signed-off-by: Wojciech Szczepanski <w.szczepansk@samsung.com>
> PopupToast: Fix text overload

- src/css/profile/wearable/changeable/theme-circle/arclistview.less
- src/js/profile/wearable/widget/wearable/ArcListview.js
- tests/js/profile/wearable/widget/wearable/ArcListview/ArcListview.js
[Problem] Listview: Text blink when tap on outside
[Solution] Not used carousels items captured the tap events.
This caused the issue in widget. Not used carousel items have been hidden.
> Listview: fix selection of item from outside

- examples/mobile/Tizen_Web_UI_FW_Globalize/js/app.js
- src/js/profile/mobile/widget/mobile/Listview.js
[Problem] In app TAU Globalization appears a gray area below the screen
[Solution] The colored listview require from developers to call method
"refresh()" on change content of the list which cause resize of list items
> Colored listview: fix a gray area below the screen

- src/css/profile/mobile/changeable/common/textinput.less
[Problem] Clear button in TextInput (X icon) overlaps the "send" button
[Solution] The fix for issue required the change of css styles
for TextInput widget with button.
> TextInput: fix issue with overlapping "send" button and "clear" button

- examples/wearable/UIComponents/contents/list/list_swipelist.js
[Issue] https://github.com/Samsung/TAU/issues/52
[Problem] UIComponents throws console errors
[Solution] In the app were bugs.
- mismatched page id in html and js code
- wrong id of listview
> UIComponents: SwipeList - bugs in example

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Problem] List divider in in non built list was treated like group index
[Solution] Use more restricted selector in less file
> Fix listview divider style on non built list

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Problem] Text longer than list width was displayed incorrectly
[Solution] Move flex styling to container element
> [Listview] Fix list content flex in non built listview

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Problem] If listitem contained some text and icon placed as image
without classes which define position of the icon
i.e. "li-has-thumb-right" icon was placed above the text.
It should be placed in row with text content
[Solution] Add styling for mentioned case
> Change flex direction of list elements placed inside 'a' tag

- examples/mobile/Tizen_Web_UI_FW_Globalize/index.html
[Issue] N/A
[Problem] Drop down menu is displayed after clicking on labels
[Solution]
Remove label tag with attribute.
Remove unused locale caption.
> Don't show drop down for labels

- src/js/core/widget/core/Page.js
[Issue] https://github.com/Samsung/TAU/issues/58 #58 
[Problem] GalleryUI (example from SDK): content is cut on bottom
[Solution] Method for calculating size of content has been changed.
If footer is not displayed then footer has size zero.
> Page (core): change calculating of content size

- src/js/core/widget/core/PageContainer.js
- tests/js/core/widget/core/PageContainer/PageContainer.js
[Problem] Page widgets were destroyed each time page history reversed.
[Solution] Destroy only widgets that are built on external pages
before removing them from DOM tree.
> Call Page Widget destroy only for external pages if reversing in history

- src/js/core/widget/core/tab/Tabbar.js
[Issue] N/A
[Problem] After selecting tab tabbar was moved to 0 position.
[Solution] Change implementation according to guide.
Set scroll to show one previous tab, exceptions:
1. First element choosen: scroll to 0
2. Last and one before last element: scroll to the end
> Tabbar: Change way of calculating tabbar position

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Issue] https://github.com/Samsung/TAU/issues/88
[Problem] Items that contained 3 line subtext dissapeared
when they were not focused
[Solution] Restore previously removed styling of 'a' elements
inside list.
> Fix dissapearing items in ArcListView

- src/css/profile/wearable/changeable/theme-circle/layout.less
- src/js/core/widget/core/Page.js
[Problem] On wearable device with circular screen if more button was placed
inside header element as an only node empty header was taking
place on the screen. More button inside header is common for
wearable rectangle screen apps.
[Solution] Change position of header to absolute if it contains only
more button on circular screen device.
> Wearable-circle: Remove header from document flow if contains only more button

- examples/wearable/Basic/index.html
- examples/wearable/List/index.html
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/46
[Problem] Header doesn't have `ui-header` class so it is broken after
saving document in design-editor.
[Solution] Add this class to header element
Signed-off-by: Kornelia Kobiela <k.kobiela@samsung.com>
> Add `ui-header` to header in wearable examples

- src/js/profile/mobile/widget/mobile/Listview.js
[Issue] N/A
[Problem] File Manager UI is differet from original app.
Background below listview is not filled.
[Solution] Before refreshing the list, the previous visible item
was not reset. This sometimes cauased issue with redraw the list.
> (mobile) Listview: Sometime colored listview doesn't refresh

- src/css/profile/mobile/changeable/common/groupindex.less
[Issue] https://github.com/Samsung/TAU/issues/119
[Problem] Radio button on listview with group index has wrong position
[Solution] Setting padding only at left is solving the issue.
> Fix for Radio button position on listview with group index

- src/js/profile/mobile/widget/mobile/DropdownMenu.js
[Issue] https://github.com/Samsung/TAU/issues/122
[Problem] Widget has frozen after refresh method
[Solution] Issue connected two bugs
- lack of protected method _getContainer in the widget
- issue in _buildFilter method, this method didn't take account
already existing elements
> DropDownMenu: fix for duplicates wrapper layer on refresh

- src/css/profile/mobile/changeable/common/groupindex.less
[Issue] https://github.com/Samsung/TAU/issues/119
[Problem] Selector for item after group index is too strong for padding
[Solution] This padding is needed to compensate width of underline for group index.
Insted of set whole padding is enough to set top and bottom padding.
> Change padding for list item after list group index

- src/js/core/widget/core/VirtualListview.js
[Issue] https://github.com/Samsung/TAU/issues/109
[Problem] Calculation of estimated height did not
include current index
[Solution] Include current index in estimation
> Mobile: Fix estimation of left element's height for virtual list

- src/js/profile/mobile/widget/mobile/Listview.js
[Issue] https://github.com/Samsung/TAU/issues/138
[Problem] Colored list background overlaps content above
[Solution]
- added condition for corner case when listview is below content.
> Listview: fix for colored background which overlaps content above

- src/css/profile/mobile/changeable/common/tabbar.less
- src/js/core/widget/core/Marquee.js
- src/js/core/widget/core/tab/Tabbar.js
- src/js/mobile.js
[Issue] N/A
[Problem] Long text in tabs are cutted and unreadable
[Solution]
- implementation Marquee widget in mobile profile
- added Marquee widget for long text in tabs
- Marquee is enabled on active tab
> Tabbar: enable Marquee widget for long texts in tabs

- examples/mobile/UIComponents/components/controls/floatingactions/index.html
- examples/mobile/UIComponents/components/controls/floatingactions/on-listview.html
- examples/mobile/UIComponents/components/controls/floatingactions/on-page.html
- examples/wearable/UIComponents/contents/empty-state/add-items-2-lines.html
- examples/wearable/UIComponents/contents/empty-state/add-items.html
- examples/wearable/UIComponents/contents/empty-state/index.html
- examples/wearable/UIComponents/contents/empty-state/no-items-2-lines.html
- examples/wearable/UIComponents/contents/empty-state/no-items.html
[Issue] https://github.com/Samsung/TAU/issues/145
[Problem] Style declarations for some pages in UIComponents app were missing.
This caused errors when page was run separately
[Solution] Add missing style declarations
> Add missing stylesheet declarations for UIComponents pages

- src/js/core/util.js
[Issue] https://github.com/Samsung/TAU/issues/141
[Problem] "pageId is not defined" error when accessing.
- inline scripts aren't executed
[Solution] Method to include html content was changed
- inline scripts are removed from loaded content
and appended to document separately
> Util: fix for execute inline scripts read from page content

- src/js/core/widget/core/Button.js
[Issue] https://github.com/Samsung/TAU/issues/154
[Problem] Button: data-inline="false" is treated as positive value
[Solution] In JS a string value "false" is treated as true
> Button: fix for positive value of data-inline="false"

- examples/mobile/UIComponents/components/controls/toggleswitch.html
- src/js/profile/mobile/widget/mobile/ToggleSwitch.js
[Issue] N/A
[Problem] ToggleSlider: Widget looks like standard toggleswitch after any style change
[Solution] Name of widget option "data-style" has changed to "data-appearance".
> (mobile) ToggleSwitch: fix for conflict data-style and style attribute

- examples/wearable/UIComponents/contents/controls/checkbox.html
[Issue]: https://github.com/Samsung/TAU/issues/161
[Problem]: Checkbox doesn't have graphics to its CSS
[Solution]: Add tau.circle.css to checkbox example itself
Signed-off-by: Kornelia Kobiela <k.kobiela@samsung.com>
> Add tau.circle.css to checkbox wearable example

- Gruntfile.js
[Issue] N/A
[Problem] After building TAU stylesheets temporaty template files left
[Solution] Add grunt task to remove unnecessary files
> Remove *.template files after building stylesheets

- Gruntfile.js
[Issue] https://github.com/Samsung/TAU/issues/165
[Problem] tau.circle.css and tau.tv.css did not have
license header included.
[Solution] Add licence header in during building TAU
> Add missing license header to profile specific stylesheets

- Gruntfile.js
[Issue] https://github.com/Samsung/TAU/issues/167
[Problem] Bundle was called only for the first given profile.
Task was interrupted because result of correct run
was passed like an error.
[Solution] Fix incorrect call and change series to parallel call
to speed up the process.
> Fix running bundle for each profile

- src/js/profile/mobile/widget/mobile/Listview.js
[Issue] https://github.com/Samsung/TAU/issues/184
[Problem] AnimationEnd event is not generated in Tizen browser.
The webkitAnimationEnd event is triggered instead.
[Solution] Add event listeners to webkitAnimationEnd too.
> Fix inability to use reorder list on device and emulator

- src/js/core/engine.js
- src/js/core/event/orientationchange.js
- src/js/core/router/Router.js
- src/js/core/widget/BaseWidget.js
- src/js/profile/wearable/widget/wearable/SwipeList.js
- tests/js/profile/wearable/widget/wearable/SwipeList/swipelist.js
[Issue] #190
[Problem] If you defer page TAU load in app,
next instance of TAU app loaded in the same iframe
is not able to build TAU app
[Solution] The issue was in Router instance.
The Router contains instance of document body element which
is uses as page container. After override content of HTML,
the Router had a wrong instance the page container.
Additional has changed method engine.stop() before build process
for stop the Router instance and remove unnecessary
event listeners.
The fixes required also method for orientation change based
throttledresize event. The listener was changed from document body
to document.
> (engine) fix for defering TAU load issue

- examples/wearable/UIComponents/css/style.circle.css
[Issue] https://github.com/Samsung/TAU/issues/216
[Problem] UIComponents: Popup not display text after select all
[Solution] Css selectors for listview were stronger then app styles.
Selectors in the app have been made stronger.
> (UIComponents) Fix for popup's look on the list with select mode

- examples/mobile/UIComponents/components/list/list-select-check.js
[Issue] https://github.com/Samsung/TAU/issues/207
[Problem] Group index doesn't work after select each dependent options
[Solution] The fix is part of UI Components application code.
In previous version was implemented use case when a user select group index checkbox.
This patch make connection also between each checkbox and group index.
If any checkbox will be unchecked then group index also will be unchecked.
> UIComponents: GroupIndex has changed if all dependent checkbox are selected

- src/css/profile/wearable/changeable/common/spin.less
- src/js/profile/wearable/widget/wearable/Spin.js
[Issue] https://github.com/Samsung/TAU/issues/209
[Problem] NumberPicker: Number is cut
[Solution] All elements inside spin widget were positioned absolutely,
this cause that's widget didn't know proper width. For properly get width
of widget we added placeholder.
> NumberPicker: Added auto width of text in Spin widget

- examples/wearable/UIComponents/contents/controls/slider/index.html
[Issue] https://github.com/Samsung/TAU/issues/211
[Problem] UIComponents: Text is cut on the list /Controls/Slider
[Solution] The solving of issue was removing unnecessary span tag.
> UIComponents: removed unnecessary tag "span" from text on list

- examples/wearable/UIComponents/contents/list/virtual/1line_btn.html
[Issue] https://github.com/Samsung/TAU/issues/227
[Problem] Buttons on list are hidden under left edge of screen.
[Solution] Sample app was unnecessary styles.
> (wearable) UIComponents: VirtualList with button looks wrong

- examples/mobile/UIComponents/components/popup/toast.html
[Issue] https://github.com/Samsung/TAU/issues/240
[Problem] UIComponents: Text in Toast popup is cut
[Solution] Text has edited.
> UIComponents: fix for cuted text in Toast popup

- src/css/profile/mobile/changeable/common/scrollview.handler.less
[Issue] https://github.com/Samsung/TAU/issues/242
[Problem] The left/right padding are not same for Horizontal Scroll handler
[Solution] Selectors in css styles have been changed to more specific.
> Fix for right padding when horizontal scroll handler is active

- src/css/profile/mobile/changeable/common/contextpopup.less
[Issue] https://github.com/Samsung/TAU/issues/250
[Problem] Contextual Popup has wrong widht
[Solution] The contextual popup width was inherit from standard popup.
This was issue. Width "auto" has added to the contextual popup.
> Contextual Popup: fix for popup width

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Issue] https://github.com/Samsung/TAU/issues/247
[Problem] UIComponents: Subtext is cut on multiline list
[Solution] Subtext lines have not ellipsis styles.
New styles were added.
> Fix for cut line of subtext on multiline list

- examples/mobile/UIComponents/components/controls/radio.js
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/126
[Problem] "The Active Radio" text wasn't initially set to the selected value
[Solution] Check which option is selected and update the text with it's value
Signed-off-by: Hubert Siwkin <h.siwkin@samsung.com>
> Display the initial state of radio checkbox

- examples/wearable/UIComponents/contents/controls/button/icon-button.css
- examples/wearable/UIComponents/contents/controls/button/icon-button.html
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/130
[Problem] Not visible button in Button example on code.tizen.org
[Solution] The issue was caused by not standard reference to icon source
in button element. Data-icon attribute is not recognized by browser.
For resolve issue, missing files was defined in app css files.
> (code.tizen.org) Fix for missed button image in examples

- src/js/profile/wearable/widget/wearable/ArcListview.js
- tests/js/profile/wearable/widget/wearable/ArcListview/ArcListview.js
[Issue] https://github.com/Samsung/TAU/issues/260
[Problem] Height was set only once - before listitem height
was set to its final value.
[Solution] Add transitionend listener for each modified
style property
> Fix Arclistview highlight height

- src/css/profile/mobile/changeable/common/expandable.less
- src/js/profile/mobile/widget/mobile/Expandable.js
[Issue] https://github.com/Samsung/TAU/issues/273
[Problem] Expandable List: After expanding list a back required twice press
[Solution] The issue was caused by implementation of keyborad support in tv profile.
Adding "href='#'" attribute without "tabindex='0'" caused history change.
The issue was solve by adding "tabindex" attribute.
> Expandable list: fix for history change on toggle switch press

- examples/mobile/UIComponents/components/navigationelements/indexscrollbar.js
- examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.js
- src/js/profile/mobile/widget/mobile/IndexScrollbar.js
[Issue] https://github.com/Samsung/TAU/issues/268
[Problem] IndexScrollbar: Scrollbar item and list position is different
[Solution] Inside index were white spaces which changing widget running.
Text content was trimmed by js code in index and samples.
> IndexScrollbar: Cleaning of white spaces from index

- src/js/core/widget/BaseWidget.js
- src/js/core/widget/core/Button.js
[Issue] https://github.com/Samsung/TAU/issues/266
[Problem] UIComponents: Button with icon in header is not visible
[Solution]
Several issue with setting of widget option were fixed.
- fix for wrong condition for textContent,
- fix for wrong setting for size option
- fix for wrong inline option recognition
Added new option "enabledIcon".
Added method for recognition common attributes eg. "ui-inline"
Added method for widget specific attributes like "ui-btn-icon"
> Button: Fix for css classes indicating on using of icon in button

- src/js/profile/mobile/widget/mobile/Listview.js
[Issue] https://github.com/Samsung/TAU/issues/272
[Problem] Listview: Second listview has wrong color
[Solution] Filter for sibling lists has been improved.
> Listview: fix for color list with embedded lists

- src/js/profile/mobile/widget/mobile/Listview.js
[Issue] https://github.com/Samsung/TAU/issues/279
[Problem] MoreMenu: After popup open the first item is highlighted
[Solution] Check keyboardSupport config before focus set
> Listview: disable focus on list items when keyboardSupport disabled

- src/css/profile/wearable/changeable/theme-circle/marquee.less
[Issue] https://github.com/Samsung/TAU/issues/281
[Problem] Styling caused only misalignment
in 5 items arclistview
[Solution] Remove unnecessary styling
> Remove unnecessary styling

- src/js/core/widget/core/tab/Tabbar.js
[Issue] https://github.com/Samsung/TAU/issues/301
[Problem] Setting the same active tab
again caused focus loss.
[Solution] Do not perform action if tab
is already set as active one.
> Tabbar: Skip action if desired tab is already active

- src/css/profile/mobile/changeable/common/slider.less
- src/js/core/widget/core/Slider.js
[Issue] https://github.com/Samsung/TAU/issues/278
[Problem] Vertical slider could not be moved because
actual range input element had different dimensions
and orientation than displayed one.
[Solution] Change slider dimensions and add css styling
for vertical slider
> Fix vertical input slider

- src/css/profile/mobile/changeable/common/listview.less
[Issue] https://github.com/Samsung/TAU/issues/271
[Problem] Listview: Colored items texts are brightened after scroll
[Solution] For resolve issue enough to change z-index for colored background.
> Listview: fix for colored background overshadows text content

- src/js/profile/wearable/widget/wearable/Slider.js
[Issue] https://github.com/Samsung/TAU/issues/283
[Problem] Slider doesn't suppport mouse in TAU Design Editor and code.tizen.org
[Solution] The mouse support has added.
> Slider: add support for mouse events

- examples/mobile/UIComponents/components/navigationelements/pageindicator.html
- examples/mobile/UIComponents/components/navigationelements/pageindicatorDotted.html
- src/js/core/widget/core/PageIndicator.js
[Issue] https://github.com/Samsung/TAU/issues/270
[Problem] Option named style was conflicting with style parameter of element
[Solution] Rename style option to appearance
> PageIndicator: Change conflicting option name

- src/js/profile/mobile/widget/mobile/DropdownMenu.js
[Issue] https://github.com/Samsung/TAU/issues/275
[Problem] DropDownMenu: Press effect remains after select
[Solution] Check keyboardSupport before focus set
> DropDownMenu: disable focus when keboardSupport is disabled

- examples/wearable/UIComponents/contents/controls/processing/small_processing.html
- examples/wearable/UIComponents/contents/controls/processing/small_processing.js
[Issue] https://github.com/Samsung/TAU/issues/284
[Problem] The newest versions of browsers block evaluation of
inline js scripts which were loaded with HTML content by XMLHttp request
[Solution] Inline script has been changed to file.
> Fix for example Processing small in UIComponents

- src/css/profile/wearable/changeable/theme-circle/processing.less
[Issue] https://github.com/Samsung/TAU/issues/285
[Problem] Maximum width was set less than screen width.
[Solution] Override maximum width and height style.
> Fix cutted processing full circle

- src/js/core/history.js
- src/js/core/router/Router.js
- src/js/core/router/route/panel.js
[Issue] Samsung/TAU-Design-Editor#166
[Problem] Back button not working for panels
[Solution] Generate new tauback event in history.back() which is handled by panel changer
> Fix navigation bar - back button not working

- src/js/core/util/scrolling.js
[Issue] N/A
[Problem] TAU was stopping rotarydetent event
propagation if scrolling module was enabled.
[Solution] Remove code responsible for stopping event.
> TAU was stopping rotarydetent event propagation

- src/css/profile/wearable/changeable/theme-circle/processing.less
[Issue] https://github.com/Samsung/TAU/issues/315
[Problem] ArcListview highlight effec
was overlapping processing bar
[Solution] Change z-index of processing widget
> Change z-index of full processing widget

- src/css/profile/wearable/changeable/theme-circle/listview.less
[Issue] https://github.com/Samsung/TAU/issues/280
[Problem] SnapListview had dimmed content - it was caused by
highlight drawn above of listview element
[Solution] Change z-index of highlight effect.
> Change z-index of SnapList highlight

- src/js/core/widget/core/Button.js
[Issue] https://github.com/Samsung/TAU/issues/274
[Problem] Buttons: Icon on button is not centered
[Solution] By default icon position is set to left when text content
is not empty. But buttons didn't take account white spaces.
This change makes trim() on text content to remove white spaces.
> Button: fix for icon position on button without text

- examples/wearable/UIComponents/contents/controls/toggle.html
- src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
- src/css/profile/wearable/changeable/theme-circle/toggleswitch.less
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/192
[Problem] Toggle Slider in wearable profile looks similar to toggle switch
[Solution] According to latest guidlines, ToggleSwitch should looks
like ToggleSlider. Instead of adding different look the old look of
ToggleSwitch has been changed.
> (wearable) ToggleSlider has changed look

- src/css/profile/mobile/changeable/common/tabbar.less
[Issue] https://github.com/Samsung/TAU/issues/267
[Problem] Tabs: Tab underline seems too low
[Solution] Css for text in span element inside tab with title
has been changed.
> Tabbar: fix for wrong position of Tab underline

- examples/mobile/UIComponents/components/controls/textinput.html
- src/css/profile/mobile/changeable/common/textinput.less
[Issue] https://github.com/Samsung/TAU/issues/276
[Problem] Search Input: Clear button is moved too much to right
[Solution] Css selectors for clear button position has been changed.
> TextInput: fix for postion of clear button icon in search input

- examples/mobile/UIComponents/components/headerfooter/header/twoiconscircle.html
- examples/mobile/UIComponents/components/headerfooter/index.html
- src/css/profile/mobile/changeable/common/header.less
- src/js/core/widget/BaseWidget.js
[Issue] https://github.com/Samsung/TAU/issues/222
[Problem] Button style -> circle in header is rectangle
[Solution] The header didn't allow that button has circle style,
the patch makes this possible.
> Header: add possibility to make button with circle style

- examples/wearable/UIComponents/contents/list/arclist_marquee_style.html
- examples/wearable/UIComponents/contents/list/list_marquee_style.html
[Issue] https://github.com/Samsung/TAU/issues/329
[Problem] Examples with multiline list were missing
required class. It was essential to get correct
multiline list effect.
[Solution] Add missing classes
> Add missing class in examples

- examples/mobile/UIComponents/components/controls/textinput.html
- src/js/profile/mobile/widget/mobile/TextInput.js
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/234 (TAU Design Editor)
[Problem] The input container does not describe of input field inside.
[Solution] The container is generating during build process. Widget can adds
specific class name for container in depend to input type.
- Text input examples have extended
> TextInput: added distinguished class for container in depend to input type

- src/js/profile/wearable/widget/wearable/Selector.js
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/279
[Problem] Selector item removal API that allows for removing
items by HTMLElements would be helpful.
[Solution] Extend API to accept both index and HTMLElement
> Extend Selector remove item API

- src/js/core/widget/BaseWidget.js
- src/js/core/widget/core/indexscrollbar/IndexScrollbar.js
- tests/js/profile/mobile/widget/mobile/Listview/Listview.js
[Issue] N/A
[Problem] Widgets did not react on attribute
changes after calling refresh() method.
[Solution] Read widget options from attributes
before widget refreshing.
> Add reading of widget properties during refresh

- src/js/core/widget/core/Graph.js
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/271
[Problem] tauCharts always looks for the color array
[Solution] Add missing conversion to color array
> Fix graph plot color property

- src/css/profile/mobile/changeable/common/floatingactions.less
[Issue] https://github.com/Samsung/TAU/issues/348
[Problem] Floating Button is too wide
[Solution] css selectors have been changed to more specific ones
> FloatingActions: fix for button width

- src/js/core/engine.js
[Issue] Refer to https://github.com/Samsung/TAU-Design-Editor/issues/272
[Problem] When wiget has wrapper developer cannot find widget instance by getBinding method.
[Solution] Added possibility to find widget instance by widget wrapper.
> engine: add getBinding instance search on widget wrapper

- tests/js/core/widget/core/Graph/Graph.html
- tools/grunt/tasks/tests.js
[Issue] N/A
[Problem] Built wgt did not contain external
libraries such as tauCharts
[Solution] Add common directory from dist and
change file references in test files
> Add common files to tct test packages

- src/js/core/event/vmouse.js
[Issue] N/A
[Problem] DOM method "elementFromPoint" receives wrong arguments
and throws exception
[Solution] Added arguments verification before DOM method call
> Events/vmouse: method handleTouchMove doesn't ready for broken data

- tests/js/core/widget/core/Checkbox/api/Checkbox.html
- tests/js/core/widget/core/Checkbox/api/Checkbox.js
- tests/js/core/widget/core/Radio/api/Radio.html
- tests/js/core/widget/core/Radio/api/Radio.js
[Issue] N/A
[Problem] Part of HTML in tests are loaded by synchronous XHTTPRequest,
this cause issue.
[Solution] Added HTML sample to Checkbox.html. Old code cannot be removed
because is used by Karma test engine.
> (tests) RadioButton & Checkbox: fix for depracated API synchronous XHTTPRequest

- src/css/profile/wearable/changeable/theme-circle/theme.changeable.less
[Issue] N/A
[Problem] Listview selection style has changed, the highlight on press
effect was used from previous listview style.
[Solution] Change highlight color, because of we currently do not have
color table temporaty set hihglihght color with rgb value.
> Change snaplist press effect background color
